# Generated by Django 5.2.7 on 2025-11-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComparAPP_WEB', '0003_orden_detalleorden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_casino',
            field=models.IntegerField(default=0, verbose_name='Precio Casino'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_castano',
            field=models.IntegerField(default=0, verbose_name='Precio Castaño'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_foodtruck',
            field=models.IntegerField(default=0, verbose_name='Precio Foodtruck'),
        ),
    ]
