# Generated by Django 5.2.7 on 2025-12-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComparAPP_WEB', '0004_remove_producto_precio_producto_precio_casino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_casino',
            field=models.IntegerField(default=0, verbose_name='Stock Casino'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_castano',
            field=models.IntegerField(default=0, verbose_name='Stock Castaño'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_foodtruck',
            field=models.IntegerField(default=0, verbose_name='Stock Foodtruck'),
        ),
    ]
